### ISSUE TITLE
placement of zones changes randomly

### ISSUE THREAD

**Issue by kpande** [psieg/Lightpack#155]
sometimes the placement of the light zones will move. i've got 3 monitors, two side-by-side and one on top of those two centred in the middle. my zones should be placed on the top monitor always but it will move down to straddle the bottom two monitors after some condition I haven't been able to determine. I can move the zones back so the capturing works once again but eventually I notice it's no longer capturing the right monitor.

**Comment by psieg** [comment]
I assume you turn of the screens or windows does so? Then it's #84 and #140.
If not, please try to find out when exactly it happens.

**Comment by kpande** [comment]
it happens when I log in, and when the screen locks for screensaver without blanking. I don't turn off screens but if I do switch my third (Prismatik-enabled) monitor to another input then the blocks will definitely move when I switch it back to the Linux input and everything resets.

**Comment by psieg** [comment]
This is probably the same as the other zone placement issues - the resolution changes make the desktop manager resize/move the capture windows.

**Comment by psieg** [comment]
Should be fixed with the latest release

**Comment by kpande** [comment]
it is not fixed, unfortunately. i build git master and this still happens - I've got 3 monitors in a triangle shape and the top one is used for a windows VM on its own GPU. when I switch back to Linux input (a different GPU) KDE rearranges all the windows and I've never figured out how to stop it. it's very frustrating. I know it's not this program's fault.

**Comment by psieg** [comment]
okay... can you please turn up the log level (1 should be sufficient) and do the switch (in both directions) and then provide the log? seeing the changes as provided to Prismatik may help find a solution.

**Comment by psieg** [comment]
@kpande ping

**Comment by kpande** [comment]
@psieg I haven't been able to start it in a debug state while also reproducing the issue, it's finicky. I do notice that sometimes when it starts up all the zones are in the correct place, and other times they are wrong. it may be a race condition.

**Comment by kpande** [comment]
I found a workaround to restart the program when the layout changes repeatedly and it restores from config file which places them properly

**Comment by DPattee** [comment]
My multi-monitor zones change 'randomly' on 5.11.2.17 Mac Mojave.

Sometimes it is when I take an app in to 'native fullscreen mode', other times it is when the screensaver puts the monitors to sleep. It isn't every time that I do either of those 2 things, but it is often enough that I have started just automatically quitting/restarting Prismatic every time I wake the computer back up. 

It is currently in a 'jumbled' state, I just turned 'experimental' on so I could see the 'logging' level. it is set to 1, I'll let it run for a bit, quit/restart it to 'fix' the arrangement, and then wait for it to 'jumble' again then will attach logs here.

**Comment by psieg** [comment]
It should be next to the profile data, under your home directory (`QDir::homePath()`)

**Comment by kpande** [comment]
fwiw this issue is 'resolved' in that I can restart Prismatik and the zones are replaced properly.

however, when I login to KDE (every time) they are on the wrong monitor until I restart the program.
