### ISSUE TITLE
Portrait mode error

### ISSUE THREAD

**Issue by 34justice** [psieg/Lightpack#253]
Hi,
On windows 10, in portrait mode, I have the following error: 

`19:37:34:208 Critical: enum GrabResult __cdecl DDuplGrabber::grabScreens(void) Dimension mismatch: screen 1024 x 1280, texture 1280 x 1024
19:37:34:258 Debug: enum GrabResult __cdecl DDuplGrabber::grabScreens(void) Lost Access to desktop 0x10001 : 0x887a0001 , requesting realloc`

**Comment by RonnieViklund** [comment]
Same here:

19:29:51:967 Critical: enum GrabResult __cdecl DDuplGrabber::grabScreens(void) Dimension mismatch: screen 1440 x 3440, texture 3440 x 1440
19:29:51:967 Debug: enum GrabResult __cdecl DDuplGrabber::grabScreens(void) Lost Access to desktop 0x10001 : 0x887a0001 , requesting realloc
19:29:51:983 Debug: void __cdecl GrabberBase::grab(void) reallocating

**Comment by psieg** [comment]
This should be rather simple. I'll try to include it in the next release, but I don't get around to doing a lot for Prismatik currently unfortunately.

**Comment by psieg** [comment]
Fixed in 5.11.2.20

**Comment by Wa1den** [comment]
Hi, still getting this issue on 5.11.2.30.
Win11 two display config where first one is in landscape and second is in portrait mode. 
With "WinAPI" grab mode everything works good but performance is very low but with "Win8 desktop duplication" mode lights just randomly flash every few seconds.
When the second display is in landscape mode "Win8" mode works fine.
